[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
skip = ["node_modules"]
remappings = [
  "@somnia-chain/reactivity-contracts/=node_modules/@somnia-chain/reactivity-contracts/",
  "@somnia-chain/reactivity-contracts/contracts/SomniaEventHandler.sol=src/vendor/SomniaEventHandler.sol",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
skip = ["node_modules"]
remappings = [
  "@somnia-chain/reactivity-contracts/=node_modules/@somnia-chain/reactivity-contracts/",
  "@somnia-chain/reactivity-contracts/contracts/SomniaEventHandler.sol=src/vendor/SomniaEventHandler.sol",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[fuzz]
runs = 512
